name: Download CSV

on:
  workflow_dispatch:   # Allows you to trigger manually from GitHub UI

jobs:
  download_csv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas psycopg2-binary

    - name: Download CSV
      run: |
        python download_data.py

    - name: Commit CSV
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add cpi_long_with_location.csv
        git commit -m "Update CSV"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
